### ISSUE TITLE
Provide vs code config file

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-examples#1]
it will allow to have extension directly recommended or installed  when opening the repository.

As first iteration I think we should specify only the VS Code Kaoto extension.

On long run, when we will ensure it is working better, we can provide the Extension pack for Camel so that we can also run the integration easily.

**Comment by lordrip** [comment]
Would this [extensions.json](https://github.com/KaotoIO/kaoto-examples/blob/e886a54765710005089f42c518a08952f71f96ed/.vscode/extensions.json) file help?

**Comment by apupier** [comment]
yes, it is this file

**Comment by lordrip** [comment]
Ok, then I'll close this issue since we have it already :+1:
